- name: Javascript
  logo: javascript
  url: https://www.javascript.com/
  color: F1E05A
  projects:
          - url: https://github.com/201411108/Mutnemom
          - url: https://github.com/201411108/WhereWeMeet

- name: Typescript
  logo: typescript
  url: https://www.typescriptlang.org/
  color: 3178C6
  projects:
          - url: https://github.com/jiminAn/Coin_Auto_Traiding
          - url: https://github.com/201411108/global-navigation-bar
          - url: https://github.com/201411108/react-typescript-bolierplate
          - url: https://github.com/201411108/Remoters

- name: React
  logo: react
  url: https://ko.reactjs.org/
  color: 61DAFB
  projects:
          - url: https://github.com/jiminAn/Coin_Auto_Traiding
          - url: https://github.com/201411108/global-navigation-bar
          - url: https://github.com/201411108/react-typescript-bolierplate
          - url: https://github.com/201411108/Remoters

- name: ReactNative
  logo: react
  url: https://reactnative.dev/
  color: 61DAFB
  projects: 
          - url: https://github.com/201411108/WhereWeMeet

- name: Swift
  logo: swift
  url: https://swift.org/
  color: E45530
  projects:
          - url: https://github.com/201411108/swiftUI_tutorial
          - url: https://github.com/201411108/dodoList

- name: Java
  logo: java
  url: https://www.java.com/
  color: E0234E
  projects:
          - url: https://github.com/201411108/GollaHobby
          - url: https://github.com/201411108/HowElec

- name: Kotlin
  logo: kotlin
  url: https://kotlinlang.org/
  color: blueviolet
  projects:
          - url: https://github.com/201411108/Black-Android-app-for-eye

- name: Android
  logo: android
  url: https://developer.android.com/
  color: brightgreen
  projects:
          - url: https://github.com/201411108/GollaHobby
          - url: https://github.com/201411108/Black-Android-app-for-eye
          - url: https://github.com/201411108/HowElec

- name: Python
  logo: python
  url: https://www.python.org/
  color: blueviolet
  projects:
          - url: https://github.com/201411108/pharynx_detection
          - url: https://github.com/201411108/Team-K_5-Src
