- name: Javascript
  logo: javascript
  url: https://www.javascript.com/
  color: F1E05A
  projects:
          - url: https://github.com/201411108/Mutnemom
          - url: https://github.com/201411108/WhereWeMeet

- name: Typescript
  logo: typescript
  url: https://www.typescriptlang.org/
  color: 3178C6
  projects:
          - url: https://github.com/201411108/Remoters
          - url: https://github.com/201411108/free-onboarding-course

- name: React
  logo: react
  url: https://ko.reactjs.org/
  color: 61DAFB
  projects:
          - url: https://github.com/201411108/Remoters
          - url: https://github.com/201411108/free-onboarding-course

- name: React-Native
  logo: react
  url: https://reactnative.dev/
  color: 61DAFB
  projects: 
          - url: https://github.com/201411108/WhereWeMeet

- name: Swift
  logo: swift
  url: https://swift.org/
  color: E45530
  projects:
          - url: https://github.com/201411108/dodoList
          - url: https://github.com/201411108/swiftUI_tutorial

- name: Java
  logo: java
  url: https://www.java.com/
  color: E0234E
  projects:
          - url: https://github.com/201411108/GollaHobby

- name: Kotlin
  logo: kotlin
  url: https://kotlinlang.org/
  color: E0234E
  projects:
          - url: https://github.com/201411108/Black-Android-app-for-eye

- name: Android
  logo: android
  url: https://developer.android.com/
  color: E0234E
  projects:
          - url: https://github.com/201411108/GollaHobby
          - url: https://github.com/201411108/Black-Android-app-for-eye

- name: Python
  logo: python
  url: https://www.python.org/
  color: #3C78A9
  projects:
          - url: https://github.com/201411108/Team-K_5-Src
